# Generated by Django 3.2.6 on 2021-12-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fao_forest_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ELEM', models.CharField(max_length=100)),
                ('AREA_NEW', models.CharField(max_length=100)),
                ('GOAL', models.CharField(max_length=100)),
                ('value_footnotes', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('VALUE', models.IntegerField()),
                ('YEAR', models.IntegerField()),
                ('element_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='scrapingtweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
    ]
